{\rtf1\ansi\ansicpg1252\cocoartf1671
{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26 \cf0 \expnd0\expndtw0\kerning0
#!/bin/bash\
\
echo\'a0'First\'a0line\'a0of\'a0file_one\
Second\'a0line\'a0of\'a0file_one\
Third\'a0line\'a0of\'a0file_one'\'a0>\'a0file_one\
\
echo\'a0'First\'a0line\'a0of\'a0file_two\
Second\'a0line\'a0of\'a0file_two\
Third\'a0line\'a0of\'a0file_two'\'a0>\'a0file_two\
\
echo\'a0'First\'a0line\'a0of\'a0file_three\
Second\'a0line\'a0of\'a0file_three\
Third\'a0line\'a0of\'a0file_three'\'a0>\'a0file_three\
\
echo\'a0'First\'a0line\'a0of\'a0file_four\
Second\'a0line\'a0of\'a0file_four\
Third\'a0line\'a0of\'a0file_four'\'a0>\'a0file_four\
\
echo\'a0"content\'a0of\'a0file_one"\
cat\'a0file_one\
echo\'a0"========================"\
echo\'a0"content\'a0of\'a0file_two"\
cat\'a0file_two\
echo\'a0"========================"\
echo\'a0"content\'a0of\'a0file_three"\
cat\'a0file_three\
echo\'a0"========================"\
echo\'a0"content\'a0of\'a0file_four"\
cat\'a0file_four\
echo\'a0"========================"\
\
cat\'a0file_four\'a0>\'a0JOINTFILE\
cat\'a0file_one\'a0>>\'a0JOINTFILE\
cat\'a0file_two\'a0>>\'a0JOINTFILE\
cat\'a0file_three\'a0>>\'a0JOINTFILE\
\
echo\'a0"content\'a0of\'a0JOINTFILE"\
cat\'a0JOINTFILE\
\
echo\'a0"listing\'a0of\'a0current\'a0directory"\
echo\'a0$`ls`\
\
rm\'a0file_one\
rm\'a0file_two\
rm\'a0file_three\
rm\'a0file_four\
rm\'a0JOINTFILE\
\
echo\'a0"listing\'a0of\'a0current\'a0directory"\
echo\'a0$`ls`\
\'a0}